### ISSUE TITLE
Things To Be Done and Overcome

### ISSUE THREAD

**Issue by Ero2000** [HermanLin/Luorolin#2]
We need a way to implement a time/date system, that affects the conditions and weather one is going through, that potentially affects the situations one can encounter. Also, destinations as well, and diseases/wounds/injuries and a difficulty system.

**Comment by HermanLin** [comment]
We can implement the time/date system with a separate method that runs every time the game loop loops.  
As for the conditions, we can implement that within the Family class where it's easier to access each individual character.
The destinations can be implemented within the Game class as well and use two arrays: one that stores the town names and the other for the destinations' distances.
